# Generated by Django 4.2.7 on 2025-08-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=128)),
                ('click', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('click_per_sale', models.FloatField()),
                ('cost', models.FloatField()),
                ('sales_price', models.FloatField()),
                ('unit_profit', models.FloatField()),
                ('total_profit', models.FloatField()),
                ('profit_per_click', models.FloatField()),
                ('ts', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_metric',
            },
        ),
    ]
