# Generated by Django 4.2.7 on 2025-08-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet1',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(db_column='product id')),
                ('product_name', models.CharField(db_column='product name', max_length=128)),
                ('click', models.IntegerField(db_column='click')),
                ('sales', models.IntegerField(db_column='sales')),
                ('click_per_sale', models.FloatField(db_column='click/sales')),
                ('cost', models.FloatField(db_column='cost (₺)')),
                ('sales_price', models.FloatField(db_column='sales price (₺)')),
                ('unit_profit', models.FloatField(db_column='unit profit')),
                ('total_profit', models.FloatField(db_column='total profit')),
                ('profit_per_click', models.FloatField(db_column='profit/click')),
            ],
            options={
                'db_table': 'sheet1',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ProductMetric',
        ),
    ]
