# Generated by Django 4.2.7 on 2025-08-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sheet1_delete_productmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Businesses',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('owner_first_name', models.CharField(max_length=100)),
                ('owner_last_name', models.CharField(max_length=100)),
                ('business_phone', models.CharField(max_length=20)),
                ('owner_phone', models.CharField(max_length=20)),
                ('interest_solutions', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('interest_products', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('qr_code_url', models.CharField(blank=True, max_length=255, null=True)),
                ('service_type', models.CharField(choices=[('Basic', 'Basic'), ('Pardon+', 'Pardon+'), ('Elite', 'Elite')], default='Basic', max_length=20)),
                ('service_duration', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('service_start_date', models.DateField(blank=True, null=True)),
                ('service_end_date', models.DateField(blank=True, null=True)),
                ('pos_system_status', models.CharField(choices=[('none', 'None'), ('software_only', 'Software Only'), ('full_system', 'Full System')], default='none', max_length=20)),
                ('pos_duration', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True)),
                ('pos_start_date', models.DateField(blank=True, null=True)),
                ('pos_end_date', models.DateField(blank=True, null=True)),
                ('tax_number', models.CharField(max_length=50, unique=True)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('hotel', 'Hotel'), ('beach', 'Beach'), ('bar', 'Bar')], default='restaurant', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('registration_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=128)),
                ('click', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('click_per_sale', models.FloatField()),
                ('cost', models.FloatField()),
                ('sales_price', models.FloatField()),
                ('unit_profit', models.FloatField()),
                ('total_profit', models.FloatField()),
                ('profit_per_click', models.FloatField()),
                ('ts', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_metric',
            },
        ),
        migrations.DeleteModel(
            name='Sheet1',
        ),
    ]
