# Generated by Django 4.2.7 on 2025-08-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_businesses_productmetric_delete_sheet1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(choices=[('sales', 'Satış'), ('orders', 'Sipariş'), ('customers', 'Müşteri'), ('revenue', 'Gelir'), ('profit', 'Kar'), ('conversion', 'Dönüşüm'), ('satisfaction', 'Memnuniyet')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deadline', models.DateField()),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='dashboard.businesses')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_customers', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('top_selling_product', models.CharField(blank=True, max_length=200)),
                ('top_selling_category', models.CharField(blank=True, max_length=100)),
                ('peak_hour', models.TimeField(blank=True, null=True)),
                ('average_preparation_time', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_reports', to='dashboard.businesses')),
            ],
            options={
                'unique_together': {('business', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('sales', 'Satış'), ('orders', 'Sipariş'), ('customers', 'Müşteri'), ('revenue', 'Gelir'), ('profit', 'Kar'), ('conversion', 'Dönüşüm'), ('satisfaction', 'Memnuniyet')], max_length=20)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='dashboard.businesses')),
            ],
            options={
                'unique_together': {('business', 'metric_type', 'metric_name', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_customers', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('churned_customers', models.IntegerField(default=0)),
                ('average_customer_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('satisfaction_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_analytics', to='dashboard.businesses')),
            ],
            options={
                'unique_together': {('business', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='BusinessDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_orders', models.IntegerField(default=0)),
                ('daily_customers', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('revenue_trend', models.CharField(blank=True, max_length=20)),
                ('orders_trend', models.CharField(blank=True, max_length=20)),
                ('customers_trend', models.CharField(blank=True, max_length=20)),
                ('alerts', models.JSONField(blank=True, default=list)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_data', to='dashboard.businesses')),
            ],
            options={
                'unique_together': {('business', 'date')},
            },
        ),
    ]
